### ISSUE TITLE
Change re-exports to prefer "preferred modules" over current import

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/purescript-language-server#100]
I believe right now when deciding where to import re-exports, it currently prefers existing imports over anything else. I'd like to request that we prefer the "preferred modules" list. As an example, I often have `Data.Array` imported, which unfortunately re-exports a lot of Data.Foldable functions. Even though I have `Data.Foldable` listed as a preferred module, it tries to always import these general functions from `Data.Array`.

**Comment by nwolverson** [comment]
I also prefer we prefer preferred modules.

I don't tend to have much in there but I can't see why you'd want it the other way around.
