### ISSUE TITLE
0.23.1 appears to have bad build products

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/purescript-language-server#101]
I have 0.23.1 and I got this when compiling a file:
<img width="1354" alt="Screen Shot 2020-09-17 at 2 22 10 PM" src="https://user-images.githubusercontent.com/144058/93529748-4c5a1400-f8f1-11ea-83ec-39231033c79f.png">

**Comment by nwolverson** [comment]
Thanks, somehow I had a stale output file in the build that got released.

This should be resolved in 0.14.2 (vscode 0.23.2)
