### ISSUE TITLE
Doesn't work on Neovim past version 0.12.9 with ALE

### ISSUE THREAD

**Issue by ursi** [nwolverson/purescript-language-server#102]
I've been having trouble for some time getting this to work on my new computer and I just couldn't figure out why. Turns out, my old computer was running `0.12.9` and it looks like version 0.13 and 0.14 both doesn't seem to work for me. using `0.12.9` on my new computer works exactly how it used to. I can get it to work with ALE on `0.12.9` only, and I can't get it to work with CoC on any of the versions I tested (copying the example config into the `languageserver` field of my `coc-settings.json` and adding `"purescript"` to my `coc.preferences.formatOnSaveFiletypes`).

**Comment by nwolverson** [comment]
Please provide your config, a description of what you were doing to test the language server support (ie what was observed to "not work", and a trace of the communication to/from the language server.

**Comment by ursi** [comment]
> and a trace of the communication to/from the language server.
This would be very helpful! How do I do that?

**Comment by ursi** [comment]
Okay, I figured out the issue with CoC. However I'm not going to close this yet because it still doesn't work with ALE. Feel free to close this if you don't care about supporting ALE anymore.

**Comment by nwolverson** [comment]
What was the issue with CoC? This could be useful to others, and determining if there is some issue with the language server.

There is no question of "care about supporting ALE" - I'll happily consider changes to resolve any issues with any actively maintained LSP client - if some users of that client can provide sufficient info to identify them. I'm also keen to get a sample config for the README.

To get a trace of communication to the language server - your LSP client (ie ALE etc) should provide a way of doing this, consult its documentation.

**Comment by ursi** [comment]
> What was the issue with CoC? 

It was just a stupid mistake due to the nature of configuring with json. I had copied over the example config and accidentally nested it inside the language server above it, although it was indented such that it looked like it was a separate entry, so it was a matter of noticing that there was a single missing `}`, that didn't even throw a syntax error.

**Comment by i-am-the-slime** [comment]
@ursi Can this be closed? I use neovim with this these days.

**Comment by ursi** [comment]
seems like it, yes
