### ISSUE TITLE
Fix all import warnings but leave e.g prelude open

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-language-server#108]
With multiple open imports, we have a suggestion to fix each of them. Fix all import warnings should leave one of these (ie Prelude) alone

**Comment by andys8** [comment]
Would be neat. 

Current workaround for this is a shell script with:

```
find src test -type f -name '*.purs' -exec sed -i 's/import Prelude (.*/import Prelude/' {} \;
```
