### ISSUE TITLE
Verify builds with 0.14.x compiler

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-language-server#111]
> Things that were outputted via stderr have been switched to stdout. Thus, some tooling (e.g. purescript-psa) needed to be updated to handle this fact. Fortunately, this tool has been updated in v0.8.0 to handle both v0.13.x and v0.14.x PureScript compiler releases.

Should check what our build command parsing looks like and it's suitable. I recall it's pretty lax about "finding some json output somewhere" but don't recall if it looks in both stderr and stdout or not.

**Comment by i-am-the-slime** [comment]
This is indeed a problem. It currently only looks in stderr. I just ran into it. I guess the best would be to find out the version of the compiler and then look in the appropriate channel based on that?

**Comment by nwolverson** [comment]
My plan here is just to look at both stderr and stdout opportunistically, prefer to avoid casing on version wherever possible - the json errors parsing already skips past junk looking for lines that start JSONy and tries to parse that. I think being permissive can avoid issues with other tools that might be in the way passing that output along (whether psa, spago, some makefile or whatever).

**Comment by thomashoneyman** [comment]
There were related changes made in `psa` in https://github.com/natefaubion/purescript-psa/pull/44 and https://github.com/natefaubion/purescript-psa/pull/49; I'm not sure if either of those will be helpful in language server support for PureScript 0.14.

**Comment by nwolverson** [comment]
Release is out with basic changes for the build output and a completion issue (the removal of Kind). Some tidying and improvement to do but hopefully nothing urgent
