### ISSUE TITLE
Prioritize "Organise Imports" action lower than others

### ISSUE THREAD

**Issue by andys8** [nwolverson/purescript-language-server#113]
## Issue

Having a non imported function, code actions can be used to import it. With recent changes "organize imports" is at the top of the list

![image](https://user-images.githubusercontent.com/13085980/100130660-48afb400-2e83-11eb-89ce-d78e6631b469.png)

## Proposed Solution

Prioritize "Organize Imports" lower regarding the list position. In the example "Import spy (Debug.Trace)" is what the user is likely gonna do.

**Comment by nwolverson** [comment]
I assume this is just based on the ordering of the actions, can easily change that. FYI this action doesn't appear in vscode, because it filters out `source.organizeImports` code action kind to a separate menu

**Comment by andys8** [comment]
Would moving "Organise imports" to the end of the list be fine for you?

**Comment by nwolverson** [comment]
Yep, that's the plan - just not been pushing code recently.
