### ISSUE TITLE
Add a "Fix all import warnings" command

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/purescript-language-server#12]
I often am left with import warnings, and it would be nice if we could fix these all in one go.

**Comment by nwolverson** [comment]
Added in 2b33ab63c42428f02c091d1063050fc35c9456e1.

I added 2 flavours, fix all suggestions, and all import suggestions.

![screen shot 2018-03-12 at 22 43 01](https://user-images.githubusercontent.com/2770891/37313391-e1d6ea42-2646-11e8-89cf-76b1a46fb3cb.png)

**Comment by natefaubion** [comment]
Woah, nice! Is this available as a command I can invoke from the command palette?

**Comment by nwolverson** [comment]
No, it's a code action, which is fed by the diagnostics
