### ISSUE TITLE
Formatter (case split): extra new lines are created between cases after formatting

### ISSUE THREAD

**Issue by raptazure** [nwolverson/purescript-language-server#122]
Extra new lines are created between cases after formatting, such as:
![image](https://user-images.githubusercontent.com/44319278/107871155-1938a280-6eda-11eb-8d8e-ad58225ab7ac.png)

Instead of:
![image](https://user-images.githubusercontent.com/44319278/107871153-10e06780-6eda-11eb-8364-88426fbe037b.png)

And the latter seems more elegant and tidy (Idris / Agda and other languages that support case-split usually obey this format). Is there a way to avoid adding newlines after formatting? Thanks for answering!

**Comment by nwolverson** [comment]
I see you have [raised an issue with purty](https://gitlab.com/joneshf/purty/-/issues/232) so going to close this here.
