### ISSUE TITLE
Can't import operator with code action

### ISSUE THREAD

**Issue by andys8** [nwolverson/purescript-language-server#127]
## Issue

```
module NewModule where

x = "a" ^ "b"
```

![image](https://user-images.githubusercontent.com/13085980/111391338-b1ca6a00-86b4-11eb-8724-3405aedd69a2.png)

It does offer the action. Importing won't add it though.

### Additional information

![image](https://user-images.githubusercontent.com/13085980/111391399-da526400-86b4-11eb-822e-332d907f4f77.png)

With auto completion `import ClassNames ((^))` will correctly be added.

And also the code action does seem to work for other operators like `&&` and `+`. So it looks like it wouldn't work for certain operators (e.g. `(^)`).

**Comment by nwolverson** [comment]
This works fine for me, with the classnames example, both auto complete and the code action.

Can you share the language server version, PureScript version, being used - I suspect this may be an issue just with pre-0.14 PS / pre 0.15.0 language server, in the case where you have the same operator in multiple namespaces available for import. See #118

**Comment by andys8** [comment]
Languageserver 0.15.0 (purs 0.13.8) shows an error message:

![image](https://user-images.githubusercontent.com/13085980/113214433-c5133300-9279-11eb-874c-fbedc32f6ec9.png)

Couldn't test with purs 0.14.0 though.
