### ISSUE TITLE
Error with Neovim Nightly builtin lsp

### ISSUE THREAD

**Issue by gasacchi** [nwolverson/purescript-language-server#129]
Hi, i don't know if  i should open the issue here, since i'm stuck so forgive me
i try to use purescript-language-server with neovim builtin lsp [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) and use [nvim-compe](https://github.com/hrsh7th/nvim-compe) for code completion, but didn't work as expected.
when try to type, it give me an error:
```
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys                       
Error executing vim.schedule lua callback: error converting argument 2
```

i don't know this is neovim or purescript-language-server issue, someone already open issues on neovim 
neovim/neovim#13829

**Comment by nwolverson** [comment]
As it seems like the response is within the protocol, and the linked issue reports another language server shows the same issue, I assume it's a client issue.

Not sure it's particularly important where we're using nulls here, but I have a feeling it crops up in a number of places

**Comment by gasacchi** [comment]
thank for the response, maybe the best choice to use it with vim is Coc, i'll be try observing the issue on client side and post here when it fixed

**Comment by nwolverson** [comment]
I think coc is what people are generally using right now (that I know use vim and purescript LS)

**Comment by gasacchi** [comment]
yes, but there is a lot of people that try to move to builtin lsp, because neovim upcoming 0.5 release. well it consider "nightly" so.
still waiting official release for 0.5

**Comment by nwolverson** [comment]
I believe this is now resolved, the linked issue is closed.
