### ISSUE TITLE
Interface for applying typed holes

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/purescript-language-server#14]
It would be nice to parse the typed holes from the error, and provide a command which let's us interactively replace them.

**Comment by kRITZCREEK** [comment]
No need to parse, the JSON format contains structured information.

**Comment by natefaubion** [comment]
Oh great! I was under the impression that it wasn't available yet. Neato.

**Comment by nwolverson** [comment]
Might be an idea to add this to https://github.com/purescript/purescript/blob/master/psc-ide/PROTOCOL.md#rebuild - I think psc-ide smuggles in extra information so this wouldn't be available from a regular `purs compile` build (verified I see a `pursIde.{completions, name}` coming through

**Comment by nwolverson** [comment]
Implemented in 043981985aec8f5a2eef29986903bd027e1c8ce9 (with support from client-side extension)
![fill-hole](https://user-images.githubusercontent.com/2770891/37313526-8c9a2476-2647-11e8-9813-c8c8636eb240.gif)
