### ISSUE TITLE
Output of build tool errors

### ISSUE THREAD

**Issue by wclr** [nwolverson/purescript-language-server#150]
```
spago build -u --json-errors
```
May output such error message:
```
[error] The following packages do not exist in your package set:
[error]   - simple-json
```

Due [to this](https://github.com/nwolverson/purescript-language-server/blob/master/src/IdePurescript/Build.purs#L106) LS outputs not very informative notification: 

```
Problem running build: didn't find JSON output
```

I believe for DX it would be better to output particular errors produced by the build tool.

How do you think it would be better to handle it? Some small problems I see here:

- output may require to strip asni sequences (used for coloring) - can be just handled with `strip-ansi` npm package.
- output may be in multiple lines (and for example vscode notifications API supports only one line message, it strips away newlines)

**Comment by nwolverson** [comment]
Made a change to simply output (truncated) stderr output on error, *if* no JSON output is found.

Errors that result in something useful on stderr output, but still produce JSON from the compiler build, can't really be distinguished for a regular failed build, so I can't see any improvement there.

Any specific examples to improve welcome, at least the original case is better now.
