### ISSUE TITLE
Auto import suggestions do not work (sometimes)

### ISSUE THREAD

**Issue by wclr** [nwolverson/purescript-language-server#164]
I quite sometimes now meat the situation when auto import suggestions do not work.

![image](https://user-images.githubusercontent.com/736697/143772512-78185a01-240f-428a-8087-df6b95944fa5.png)

I see nothing particular in the log, and didn't dig it not it, any suggestions on what can go wrong?

**Comment by wclr** [comment]
Seems it doesn't work if the unkown token comes after the bracket: `(` or `[`.

**Comment by nwolverson** [comment]
I can reproduce that, thanks

**Comment by wclr** [comment]
To fix that, need to handle additional tokens:
```
              TokLeftParen -> go $ TokenStream.step str
              TokLeftSquare -> go $ TokenStream.step str
```
https://github.com/nwolverson/purescript-language-server/blob/master/src/IdePurescript/Tokens.purs#L46

I can add PR.

**Comment by nwolverson** [comment]
Why does that not just happen on the next iteration, is the "point" that is called into this function the location of the paren? Seems like the real cause must be upstream - maybe an off by one

**Comment by wclr** [comment]
Ok, I didn't figure it out carefully. This would be fixed with just making operator inclusive in `else if column >= endCol then`.

**Comment by nwolverson** [comment]
That seems to work out, I can verify it fixed the above. Thanks!
