### ISSUE TITLE
Lenses and inlined types

### ISSUE THREAD

**Issue by wclr** [nwolverson/purescript-language-server#166]
I believe we don't need signature lenses for such a case:

![image](https://user-images.githubusercontent.com/736697/144707022-a05146e7-616a-4398-ac6e-d0332fde0745.png)

**Comment by nwolverson** [comment]
Does the compiler suppress the declaration type warning in this case?

**Comment by natefaubion** [comment]
> Does the compiler suppress the declaration type warning in this case?

Yeah, at this point in type checking
```purescript
x :: Int
x = 42
```
Has been desugared into
```
x = 42 :: Int
```
So there's no difference to the compiler.

**Comment by nwolverson** [comment]
Thanks @natefaubion, I didn't realise that. In fact I've never come across any code formatted like this either.

In which case I fully agree, we shouldn't show a lens in this situation.

**Comment by thomashoneyman** [comment]
> In fact I've never come across any code formatted like this either.

I mostly see it in modules that define proxies or constants, like

```purs
_foo = Proxy :: Proxy "foo"
```
