### ISSUE TITLE
Docs: Update formatter section

### ISSUE THREAD

**Issue by andys8** [nwolverson/purescript-language-server#179]
Hey :)

I was searching for a way to disable the formatter and there is `none` - which is great.

https://github.com/nwolverson/purescript-language-server/blob/ff6aa80bd467abe387a6d67dacb1cba8082ffeb9/src/LanguageServer/IdePurescript/Config.purs#L197-L205

By doing that I noticed the README section about the formatting provider doesn't mention the existence of other formatters than `purty`. It's just a tiny bit outdated and could be reworded to not only be about `purty`.

https://github.com/nwolverson/purescript-language-server#formatting-provider

**Comment by nwolverson** [comment]
Done debd5f0148e8749fa8cbc6c875b742a992bcd6cb
