### ISSUE TITLE
Find references returns no references

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/purescript-language-server#201]
I'm currently using VSCode with purs 0.15.7. On 0.26.2, find references almost never works. Occasionally I've gotten some results, but I have yet to determine why that might be the case. Works fine in 0.26.1.

**Comment by postsolar** [comment]
I can reproduce with VSCode and PS 0.15.10 + extension of the same version. It also doesn't work for me in Helix editor, where just the LSP (0.17.2) is used.
