### ISSUE TITLE
YouCompleteMe / Vim Plugin?

### ISSUE THREAD

**Issue by dakom** [nwolverson/purescript-language-server#37]
Just wondering - I opened a ticket at https://github.com/Valloric/ycmd/issues/1065 but I thought you might know if some work has already been done on this somewhere...?

**Comment by nwolverson** [comment]
Not aware of it, as far as I know PS vim users are using [psc-ide-vim](https://github.com/FrigoEU/psc-ide-vim) which goes directly to `purs ide server` (which this LSP server is basically a middleman for).

**Comment by dakom** [comment]
okay cool - closing this for now. Thanks :)
