### ISSUE TITLE
Data constructor import when type is already imported

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-language-server#60]
(From slack)

> unknown data constructor X” and you already have an import for the type (e.g. X) it won’t change it to X(..) when you tell it to import it?

**Comment by i-am-the-slime** [comment]
I was just about to report this because it hits me multiple times per day.

**Comment by nwolverson** [comment]
This only seems to be the case when the dctor & type have the same name

**Comment by nwolverson** [comment]
My last comment is in fact incorrect, but observes a second additional issue - we don't actually distinguish between types/values with the same name in the same module, and always end up with the full `(...)` import (assuming the dctor has the same name as its own type, not a different one...)

Fix for both incoming.

**Comment by nwolverson** [comment]
The change for this was reverted, it was causing issues due to incorrect classification of identifier namespaces.
