### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by soywod** [nwolverson/purescript-language-server#61]
[haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) proposes to format the code via [brittany](https://github.com/lspitzner/brittany). It would be possible to do the same for eg. with [purty](https://gitlab.com/joneshf/purty)?

**Comment by nwolverson** [comment]
I'm as yet unconvinced whether this should be in the language server or something external with editor integration; I guess the fact that there only seems to be 1 option does lean towards simply including it.

Welcome opinions

**Comment by soywod** [comment]
Well, the text formatting is part of the [LSP spec](https://github.com/microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#textDocument_formatting), so I guess it makes sense to one.

**Comment by milesfrain** [comment]
A few related links that are mostly related to purty with vscode IDE:

There's a vscode extension for purty formatting:
https://github.com/mvakula/vscode-purty

Discussion on consolidating vscode extensions:
https://github.com/nwolverson/vscode-language-purescript/issues/10

purty issue on integration with vscode:
https://gitlab.com/joneshf/purty/-/issues/124

Discourse thread on purty integration with IDE:
https://discourse.purescript.org/t/purty-ide-integration-to-format-on-save/1272

**Comment by andys8** [comment]
In my opinion it would be nice to provide a format handler and delegate the work to `purty`. Fail if not installed. The advantage is that there is no need to configure formatting or have a plugin for putty *per editor*.

**Comment by thomashoneyman** [comment]
> I'm as yet unconvinced whether this should be in the language server or something external with editor integration; I guess the fact that there only seems to be 1 option does lean towards simply including it.

If we do end up with multiple code formatters that's also not a problem; afaik the language server API is designed to accommodate this. In VSCode, for example, if you have multiple code formatters on your system that can be used for the same language then the editor will ask you to choose which one you want to use (or it can be configured in your settings).

**Comment by andys8** [comment]
`haskell-ide-engine` (and `haskell-language-server`) give the user [configuration options](https://github.com/haskell/haskell-ide-engine#configuration) to select the formatting provider. `elm-language-server` does not because there is only `elm-format`.

One could try to detect if `purty` is on the `PATH` and conditionally set the the formatting provider capability but I haven't seen that before. I think it's easier to fail silently (log) or with an user facing error once the user executes code formatting with the language server.

**Comment by nwolverson** [comment]
I've definitely come around to the idea that we should "just do it" (before the PR :) ), can always make the option enabled in config if required.
