### ISSUE TITLE
Apply all suggestions broken for certain imports

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-language-server#67]
Seems like the suggestion to remove data constructor imports when only the type is used

1. may appear multiple times, with a single fix
2. breaks apply all (import) suggestions until resolved

**Comment by i-am-the-slime** [comment]
I think this happens in the following combination:

There's both an unnecessary import for a data constructor and some unused functions on one line:

```purescript
import Data.Maybe (Maybe(..), fromMaybe)

example :: Maybe String -> Maybe String
example = identity
```
🔝 breaks.

When they occur in isolation it works: 

```purescript
import Data.Maybe (Maybe(..), fromMaybe)
import PscIdeClient (compileCode)

example :: Maybe String -> Maybe String
example _ = Just ""
```

as well as
```purescript
import Data.Maybe (Maybe(..), fromMaybe)

example :: Maybe String -> Maybe String
example = identity

example2 = fromMaybe
```

work.

**Comment by i-am-the-slime** [comment]
After more investigation something surprising happens for the first example when specifying: "Apply suggestion" on the line in question. It does what it should and leaves us with:
`import Data.Maybe (Maybe)` the same is true for "Remove unused reference". It also produces the complete correct result.

**Comment by nwolverson** [comment]
PR #78 fixes this case for me, but the following fails:

```purescript
import Data.Maybe (Maybe(..), fromMaybe)
import Data.Maybe (Maybe(..), fromMaybe)

example :: Maybe String -> Maybe String
example = identity
```

I think this is just due to overlaps being prohibited, in this case they are still present due to not being simple duplicates. It's clear in the LSP spec that overlaps are not permitted, but I think either earlier versions of vscode allowed this or the other form of edit in the earlier LSP spec did so.

**Comment by nwolverson** [comment]
I think I have it in 3fb5f186be945fc62f81ca56df8764944b1e2103
