### ISSUE TITLE
Sort/Clean/Format imports

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-language-server#68]
(Not sure if this can be done without a purs-ide change)

Be nice to have a reformat imports command, currently I can apply import suggestions easily, but to apply the auto ordering, the easiest thing is to tab-complete a new import then remove it.

I don't think this is the same as code formatting necessarily, as this is something already done in `purs ide server`, though there is certainly overlap if a formatter works on regions rather than whole files

**Comment by andys8** [comment]
Now that we have `purty` as formatting provider: Is this issue actually about sorting? Like sorting the lines alphabetically, or the contents of explicit imports (in parens)?

This is what the emacs plugin is doing: https://github.com/purescript-emacs/purescript-mode/blob/master/purescript-sort-imports.el

**Comment by kritzcreek** [comment]
> This is what the emacs plugin is doing

That's just a leftover copy from `haskell-mode`. In most files you'll find the formatting is determined by how the IDE server formats on auto-import (all unqualified imports alphabetically, then an empty line, then all the other imports alphabetically).

**Comment by nwolverson** [comment]
Yes, I meant to invoke the IDE server standard ordering/format/normalisation.

**Comment by nwolverson** [comment]
Implemented be55250327ca1c881235b6655a2cc3b5481c3d83
