### ISSUE TITLE
Find References feature broken

### ISSUE THREAD

**Issue by sriharshachilakapati** [nwolverson/purescript-language-server#71]
Whenever I try to issue a find references command, I get this output instead.

```
[LC] [Info] [Error] Parsing the command failed. Command: {"params":{"identifier":"liftEff","namespace":"value","module":"Control.Monad.Eff.Class"},"command":"usages"} @(main:Command.Ide app/Command/Ide.hs
:187:17)
```

Using PureScript 0.12.5, latest purescript-language-server.

Client is LanguageClient_NeoVim, and invoked using the built-in function `LanguageClient_textDocument_references()` which gives references of the identifier under cursor.

**Comment by nwolverson** [comment]
This works for me with vscode/purs 0.13.5 - but should be available on 0.12.5 I believe. 

I published a new version of the language server last night - was this working prior to that change, or has this never worked for you?

**Comment by sriharshachilakapati** [comment]
I didn't update in the last two days. Will update and see.

**Comment by sriharshachilakapati** [comment]
Just updated to 0.12.9, still getting the same message.

**Comment by kritzcreek** [comment]
I just downloaded purs at version 0.12.5 and when I run it in an empty project:
```
~\code\zerotwelve> purs ide server --log-level debug
Parsed Options:
ServerOptions {_serverDirectory = Nothing, _serverGlobs = [], _serverOutputPath = "output/", _serverPort = 4242, _serverNoWatch = False, _serverPolling = True, _serverLoglevel = LogDebug, _serverEditorMode = False}
[Debug] Accepted a connection @(main:Command.Ide app\Command\Ide.hs:213:5)
[Debug] Received command: { "params": { "identifier": "liftEff","namespace": "value","module": "Control.Monad.Eff.Class" },"command": "usages" } @(main:Command.Ide app\Command\Ide.hs:223:9)
```
```
~\code\zerotwelve> purs ide client
{ "params": { "identifier": "liftEff","namespace": "value","module": "Control.Monad.Eff.Class" },"command": "usages" }
{"result":"Module not found","resultType":"error"}
```

That means it's able to parse that command just fine. Are you running an even older `purs` binary by chance?

**Comment by sriharshachilakapati** [comment]
Sorry my bad. I was in an old project and running purs 0.11.7. Working in 0.12.5. Sorry again.
