### ISSUE TITLE
Look for packages.dhall not spago.dhall at the root folder

### ISSUE THREAD

**Issue by ptwales** [nwolverson/purescript-language-server#77]
When I setup a mono-repo as described in [spago's documentation](https://github.com/purescript/spago#monorepo), I am instructed to put separate `spago.dhall` files in each subproject.  Therefore there is no `spago.dhall` at the root directory and I get [this warning](https://github.com/nwolverson/purescript-language-server/blob/523fbbea36865eb1c1e04f73f4f39ec73c04e105/src/LanguageServer/IdePurescript/Main.purs#L308) when I start my editor at the root directory.  

Moving to a subproject directory like `app1/` still fails since I no longer have a `.spago/` or `output/` folder in my working directory.

I think `purescript-language-server` should instead be checking for a `packages.dhall` file instead since it will always be at the root directory of the project and is a closer equivalent to a `bower.json` file.

**Comment by ptwales** [comment]
More issues when trying to use the language server in a spago-mono repo.
- The server will try to execute `spago sources` to get a list of sources but it needs to do `spago -x <project>/spago.dhall sources` to get the sources it needs for a project.  
  + This can be bypassed by setting the sources in `PURS_IDE_SOURCES`
  + Or it a work around would be to have a `"sourcesCommand"` option which works similarly to `"buildCommand"`.  It would also replace `"addSpagoSources"` and `"addPscPackageSources"`
- If `PURS_IDE_SOURCES` is set then the server crashes with:
  ```
  Could not start the IDE server process. Check the configured port number is valid.
  psci-ide-server error:{ code: ENOENT, errno: ENOENT, syscall: spawn node_modules/.bin/purs }
  ```
  I don't know the exact cause of this but the `.psc-ide-port` exists in `app1/` not at the project root.

**Comment by ptwales** [comment]
Eh just found a better work around.  Just create a `spago.dhall` file at the project root and have it import and include all your subprojects' sources and dependencies.  Example

```dhall
let liba =./liba/spago.dhall

let libb = ./libb/spago.dhall

let app1 = ./app1/spago.dhall

let app2 = ./app2/spago.dhall

in  { name = 
        "spago-monorepo"
    , dependencies = 
          liba.dependencies 
        # libb.dependencies 
        # app1.dependencies 
        # app2.dependencies
    , sources = 
          liba.sources # libb.sources # app1.sources # app2.sources
    , packages =
        ./pacakges.dhall
    }

**Comment by nwolverson** [comment]
Not sure what the intended process is for spago monorepos - the documentation wasn't enough for me and I've not had time to experiment - but I'm unlikely to support per-project build while opening at the top monorepo level. This language server does not have a "multi-root" support, so will not support doing something different per sub-project.

Either (which probably means both) we can support a whole-repo workflow (which is what I think your work-around does) or we can support opening the individual sub-project directory. The latter should include setting the output directory `purescript.outputDirectory`, not sure if spago will then give the correct sources, maybe there is little or nothing to do then?

The PURS_IDE_SOURCES sounds like a different issue that is not related to the monorepo, at first glance

**Comment by ptwales** [comment]
From scanning spago's issues pages, it seems like there is no canonical or even consistent way for configuring mono-repos in spago.  I think the above workaround - having a root `spago.dhall` file that defines how to build all projects in the repo - should be considered ta solution.

That said there is an issue with my example,
```dhall
, dependencies = 
          liba.dependencies 
        # libb.dependencies 
        # app1.dependencies 
        # app2.dependencies
```
would almost always result in there being multiple dependencies, and since explicity dhall prohibits any string equality functions we can't write a `unique` function to solve it.  Users will need to structure their dhall files to have a list of unique dependencies.  Something like
```dhall
, dependencies = 
          liba.dependencies 
        # libb.extraDeps 
        # app1.extraDeps 
        # app2.extraDeps 
```
might do.

**Comment by masaeedu** [comment]
@ptwales Would you mind leaving this issue open? The workaround you proposed doesn't actually work, for the reasons you outlined.

**Comment by JordanMartinez** [comment]
This problem will go away (or be less problematic) once Spago implements "targets".
