### ISSUE TITLE
Cannot find module 'vscode-uri'

### ISSUE THREAD

**Issue by milesfrain** [nwolverson/purescript-language-server#82]
I sometimes get this error if I make changes then `npm run build`. An `npm install` usually fixes things for a while, but then the error will eventually appear again.

```
src/LanguageServer/Uri.ts:1:21 - error TS2307: Cannot find module 'vscode-uri' or its corresponding type declarations.
1 import { URI } from 'vscode-uri';
```

**Comment by nwolverson** [comment]
Suspect this is related to `npm link` shenanigans - can you check with a straight install with no links - `vscode-uri` is present in `dependencies` so odd this could be inconsistent.

**Comment by nwolverson** [comment]
I think this was a build issue for development as indicated on my previous comment, and these modules/the build process have subsequently changed
