### ISSUE TITLE
goto definition not working/inconsistent in vim

### ISSUE THREAD

**Issue by s-u-m-e** [nwolverson/purescript-language-server#84]
Steps to reproduce

- Install [purescript-vim](https://github.com/purescript-contrib/purescript-vim)
- Configure `coc-settings.json` [like so](https://github.com/neoclide/coc.nvim/wiki/Language-servers#purescript)
- `npm install -g purescript-language-server`
Observed behavior
- `:CocInfo` shows that the Purescript language server has started
- Code completion/typeahead works but code navigation fails with the error `[coc.nvim] Definition not found`

However if you
- Quit vim
- Start VSCode with the `PureScript IDE` and `PureScript Language Support` plugins installed
- Start vim (same purescript project)
Observed behaviour
- `:CocInfo` shows vim finds and attaches to existing server (started by vscode)
- Code navigation works even though the `[coc.nvim] Definition not found` error flashes at the bottom of the screen.

**Comment by nwolverson** [comment]
That sounds like your VSCode and vim settings are just not the same, code navigation will only work if `purs ide` is provided the correct source globs, in particular for your dependencies.  e.g. if using Spago, set `purescript.addSpagoSources` true - you can check your config in VSCode to see what config you want to set, it should show the correct config options. 

https://github.com/nwolverson/vscode-ide-purescript/blob/master/package.json

**Comment by andys8** [comment]
@s-u-m-e Could you double check if this issue is still the same for you after https://github.com/nwolverson/purescript-language-server/pull/90 ? (Once released, or use `master`) It might have solved your issue.

If it still the case, could you add more details, and an open source repository with instructions on how to reproduce the issue? Thanks.

**Comment by s-u-m-e** [comment]
@andys8 just tried it out and code navigation works. ( The message `[coc.nvim] Definition not found` still flashes but that's another thing)

**Comment by andys8** [comment]
Can you post/link to your complete configuration? Maybe there is something duplicated and a second process answers with a negative answer?

**Comment by s-u-m-e** [comment]
@andys8 thanks for the quick response, here's my current setup

 https://github.com/s-u-m-e/nvim

**Comment by nwolverson** [comment]
I notice you have `"--config {}"` but also `purescript` under `settings`, if `settings` work then you should not set `--config` on the command line, it may prevent them from working. (You can also check the command line of the `purs ide server` process launched by the `purescript-language-server` process, if the source globs include your packages or not)

**Comment by andys8** [comment]
So, from my side it's only guessing. 


There is this line mentioning `vimmerps`:

https://github.com/s-u-m-e/nvim/blob/310f55ca0fcd55777235aeb94cbb4de53a066743/init.vim#L167

But it's not installed anymore. Could it be the case that it wasn't removed cleanly? With the described behavior it could be that two plugins or servers are executed. The language server shouldn't work and not work at the same time. Wild guess.

**Comment by s-u-m-e** [comment]
I commented out the `--config{}` line from the config, here's the output of `:CocInfo`. @nwolverson how can I check if the source globs include my packages? running `purs ide server` from the command line seems to work but there is no output

```
## Output channel: languageserver.purescript
  [Info  - 6:50:51 PM] {"processId":37477,"rootPath":"/Users/sume/tormeda/ps/purescript-book/exercises/chapter6","rootUri":"file:///Users/sume/tormeda/ps/purescript-book/exercise
  Starting with args: ["/usr/local/bin/node","/usr/local/bin/purescript-language-server","--stdio"]
  Starting with cwd: /Users/sume/tormeda/ps/purescript-book/exercises/chapter6 and using root path: /Users/sume/tormeda/ps/purescript-book/exercises/chapter6
  Got new config (client push)
  [Info  - 6:50:51 PM] Starting IDE server
  [Info  - 6:50:51 PM] Using sources from psc-package/spago packages (PURS_IDE_SOURCES not set)
  PureScript Language Server started
  [Info  - 6:50:51 PM] Resolved IDE server paths (npm-bin: false) from PATH of /Users/sume/.yarn/bin:/Users/sume/.config/yarn/global/node_modules/.bin:/Users/sume/google-cloud-sd
  [Info  - 6:50:51 PM] /usr/local/bin/purs: 0.13.8

  [Info  - 6:50:51 PM] Found existing port from file: 15912
  [Info  - 6:50:51 PM] Starting IDE server on port 15834 with cwd /Users/sume/tormeda/ps/purescript-book/exercises/chapter6
  Started IDE server (port 15834)
  [Info  - 6:50:52 PM] [Info] cachedb was changed from: Nothing, to: Just 2020-08-22 03:02:16.87983146 UTC @(main:Command.Ide app/Command/Ide.hs:205:25)
```

**Comment by nwolverson** [comment]
Use `ps` to inspect the command line of the existing process, eg `ps aux|grep purs`

**Comment by s-u-m-e** [comment]
Looks like there's only one process running which stars when I open a `.purs` file, and it stops when I exit `vim`. Everything seems to work except sometimes `goto definition` doesn't work the first time and shows the message `[coc.nvim] Definition not found` but works on the second try.

https://asciinema.org/a/R7AAhspJH15YWACKOM7AGATdi

I can close this issue since the initial problem of not being able to navigate to definition is fixed. I'm not really bothered by the error message

**Comment by andys8** [comment]
The behavior you describe is happening for me too and I guess expected. It takes some time to initially load stuff (I guess). Afterwards it start's to work. 👍

**Comment by s-u-m-e** [comment]
Initial issue is resolved
