### ISSUE TITLE
Should this repo be formatted with purty?

### ISSUE THREAD

**Issue by andys8** [nwolverson/purescript-language-server#94]
Since `purty` can now be used as formatting provider the repo could be formatted with `purty`. If you prefer having it formatted in a different way (leave it as it is), I'm fine with it, too.

If formatting, these two files will currently break, which is a little sad. It can be likely be avoided by massaging the code upfront or fixing it afterwards. 

> src/LanguageServer/IdePurescript/Assist.purs
> src/LanguageServer/IdePurescript/Main.purs

**Comment by nwolverson** [comment]
I don't see that as a worthwhile activity, no. Possibly worth doing if the modules are reorganised at some point - some code could do with moving around anyway.

**Comment by andys8** [comment]
@nwolverson I noticed working on the `purescript-language-server` project with `purescript-language-server` enabled is a bit weird, because most editor settings want to format.

Thoughts:

* Format the repository to be in line with the ls behavior
* Provide a way to disable the format functionality of the language server

**Comment by nwolverson** [comment]
"most editor settings want to format" - is this true? Format on save is something one explicitly enables with vscode (which of course means you can set it per project), it's interesting if it's the default in some editors - that sounds rather obnoxious, personally.

If this isn't something some editors can configure on a per project basis I'm happy to put in a setting to disable the format provider.

Regarding this repo I'm not sure I 100% see a benefit while purty is still conflicting with purs ide for imports, but I also don't see a particular reason not to

**Comment by andys8** [comment]
> "most editor settings want to format" - is this true?

My sentence was probably a bit too short and not good enough. There might also be biased experience in it. Most editors will have a configuration for format on save. In my experience it is per filetype by default. It might be possible to configure editors per project in that regard, but I'm not sure how many people do this. Especially for PS.

And also people might have muscle memory to trigger format all the time.

But this regarding this, I think the biggest point is that it's somewhat inconsistent that the formatting provider implemented in the project is not used or will misformat the project, if used on the project.
